# Generated by Django 3.1.4 on 2021-02-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210128_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=35)),
                ('name', models.CharField(default='', max_length=35)),
                ('email', models.CharField(default='', max_length=35)),
                ('phone', models.CharField(default='', max_length=35)),
                ('address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=150)),
                ('zip_code', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
