# Generated by Django 3.1.4 on 2021-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
