# Generated by Django 3.1.4 on 2021-02-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
